# XBox 360 wired controller
joy_teleop:
  ros__parameters:
    piloting:
      type: topic
      interface_type: "geometry_msgs/msg/Twist"
      topic_name: cmd_vel
      deadman_buttons: [0]  # Hold "A" button while driving
      axis_mappings:
        linear-x:
          axis: 2  # Left thumb (up/down)
          scale: 0.4
          offset: 0.0
        angular-z:
          axis: 1  # Left thumb stick (left/right)
          scale: 2.5
          offset: 0.0
